In [106]:
import numpy as np
import copy
import math

In [107]:
def reformInput(matA,matB):
    mat_AT = np.transpose(matA)
    leftMat = np.dot(mat_AT,matA)
    rightMat = np.dot(mat_AT,matB)
    return leftMat,rightMat

In [108]:
def diagonalDominant(matA):
    for row in range(len(matA)):
        diag_ele = abs(matA[row][row])
        Sum = 0
        for ele in range(len(matA[row])):
            if ele == row:
                continue
            Sum += abs(matA[row][ele])
        if Sum > diag_ele:
            return False
    return True
            
            

In [115]:
def gauss_seidel(matA,matB,n_iter):
    n_rowsA,n_colsA = matA.shape
    n_rowsB,n_colsB = matB.shape
    matL = copy.deepcopy(matA)
    matU = copy.deepcopy(matA)
    epxilon = 1e-09
    for i in range(len(matA)):
        matL[i][(i+1):] = 0
        matU[i][:(i+1)] = 0
    matT = np.dot(-1*np.linalg.inv(matL),matU)
    matC = np.dot(np.linalg.inv(matL),matB)
    x0 = np.ones((n_colsA,n_colsB))
    list_ret = []
    list_ret.append(x0)
    for i in range(n_iter):
        list_ret.append(np.dot(matT,list_ret[0]) + matC)
        if np.all(np.divide(abs(list_ret[1] - list_ret[0]),abs(list_ret[0])) < epxilon):
            list_ret.pop(0)
            break
        list_ret.pop(0)
    return list_ret[0]

In [138]:
n_rowA = int(input("Enter rows number for matrix A: "))
n_colA = int(input("Enter columns number for matrix A: "))
inp_matA = np.random.randint(1,99,size=(n_rowA,n_colA))

Enter rows number for matrix A: 3
Enter columns number for matrix A: 3


In [139]:
inp_matB = np.random.randint(1,99,size=(n_rowA,1))

In [140]:
inp_matA 

array([[75,  5, 58],
       [35, 22, 52],
       [76, 36, 51]])

In [141]:
inp_matB

array([[46],
       [86],
       [83]])

In [142]:
leftMat,rightMat = reformInput(inp_matA,inp_matB)

In [143]:
leftMat

array([[12626,  3881, 10046],
       [ 3881,  1805,  3270],
       [10046,  3270,  8669]])

In [144]:
rightMat

array([[12768],
       [ 5110],
       [11373]])

In [145]:
gauss_seidel(leftMat,rightMat,1000)

array([[-0.55993997],
       [ 1.52451992],
       [ 1.38573963]])

In [146]:
gauss_seidel(inp_matA,inp_matB,1000)

array([[ 2.31580190e+286],
       [ 3.79277118e+286],
       [-6.12824915e+286]])